import requests
import re
import os
import html as html_module
from urllib.parse import urlparse

# List of slugs provided by the user
SLUGS = {
    "aug-storm",
    "ssg-08-sea-calico",
    "five-seven-crimson-blossom",
    "ump-45-day-lily",
    "mp7-teal-blossom",
    "famas-sundown",
    "m4a4-dark-blossom",
    "p90-sunset-lily",
    "xm1014-banana-leaf",
    "tec-9-rust-leaf",
    "m249-jungle",
    "mp5-sd-bamboo-garden",
    "sawed-off-jungle-thicket",
    "pp-bizon-seabird",
    "mac-10-surfwood",
    "tec-9-red-quartz",
    "desert-eagle-urban-rubble",
    "sawed-off-amber-fade",
    "m4a4-urban-ddpat",
    "awp-longdog",
    "m4a4-hellish",
    "mp9-latte-rush",
    "tec-9-whiteout",
    "zeus-x27-charged-up",
    "mac-10-derailment",
    "glock-18-green-line",
    "ump-45-late-night-transit",
    "famas-2a2f",
    "xm1014-run-run-run",
    "galil-ar-green-apple",
    "p90-straight-dimes",
    "aug-steel-sentinel",
    "p250-constructivist",
    "nova-rain-station",
    "cz75-auto-copper-fiber",
    "ak-47-b-the-monster",
    "awp-crakow",
    "zeus-x27-dragon-snore",
    "dual-berettas-sweet-little-angels",
    "aug-eye-of-zapems",
    "xm1014-monster-melt",
    "mac-10-pipsqueak",
    "nova-wurst-h-lle",
    "galil-ar-metallic-squeezer",
    "glock-18-teal-graf",
    "desert-eagle-tilted",
    "m4a1-s-wash-me-plz",
    "negev-wall-bang",
    "five-seven-midnight-paintover",
    "p90-wash-me",
    "mp5-sd-neon-squeezer",
    "m4a1-s-fade",
    "glock-18-axia",
    "galil-ar-rainbow-spoon",
    "five-seven-heat-treated",
    "mp9-arctic-tri-tone",
    "ump-45-crimson-foil",
    "usp-s-alpine-camo",
    "nova-yorkshire",
    "ssg-08-zeno",
    "p250-small-game",
    "ak-47-olive-polycam",
    "famas-half-sleeve",
    "pp-bizon-cold-cell",
    "tec-9-tiger-stencil",
    "mag-7-wildwood",
    "mp5-sd-savannah-halftone",
    "awp-cmyk",
    "desert-eagle-starcade",
    "aug-lil-pig",
    "m4a4-polysoup",
    "cz75-auto-slalom",
    "p90-attack-vector",
    "ak-47-crossfade",
    "sg-553-berry-gel-coat",
    "scar-20-wild-berry",
    "xm1014-halftone-shift",
    "mp7-astrolabe",
    "galil-ar-nv",
    "famas-halftone-wash",
    "m249-spectrogram",
    "p2000-coral-halftone",
    "ssg-08-halftone-whorl",
    "m4a1-s-stratosphere",
    "ak-47-midnight-laminate",
    "usp-s-royal-guard",
    "famas-yeti-camo",
    "mp9-cobalt-paisley",
    "desert-eagle-mint-fan",
    "p2000-royal-baroque",
    "p90-reef-grief",
    "glock-18-ocean-topo",
    "zeus-x27-electric-blue",
    "m4a4-naval-shred-camo",
    "negev-sour-grapes",
    "five-seven-sky-blue",
    "galil-ar-robin-s-egg",
    "dual-berettas-rose-nacre",
    "xm1014-gum-wall-camo",
    "nova-turquoise-pour",
    "tec-9-blue-blast",
    "mp9-buff-blue",
    "r8-revolver-cobalt-grip",
    "mac-10-storm-camo",
    "sg-553-night-camo",
    "sawed-off-runoff",
    "galil-ar-grey-smoke",
    "mp5-sd-lime-hex",
    "p250-plum-netting",
    "ssg-08-grey-smoke",
    "p90-blue-tac",
    "awp-green-energy",
    "m4a4-sheet-lightning",
    "glock-18-glockingbird",
    "ak-47-wintergreen",
    "usp-s-tropical-breeze",
    "mac-10-poplar-thicket",
    "mp5-sd-gold-leaf",
    "xm1014-copperflage",
    "ak-47-varicamo-grey",
    "dual-berettas-polished-malachite",
    "tec-9-garter-9",
    "galil-ar-acid-dart",
    "p2000-marsh",
    "p90-mustard-gas",
    "ssg-08-tiger-tear",
    "mac-10-acid-hex",
    "r8-revolver-leafhopper",
    "ssg-08-green-ceramic",
    "p250-copper-oxide",
    "famas-palm",
    "ump-45-green-swirl",
    "tec-9-raw-ceramic",
    "mp9-pine",
    "negev-raw-ceramic",
    "zeus-x27-swamp-ddpat",
    "m249-sage-camo",
    "g3sg1-green-cell",
    "mag-7-copper-oxide",
    "aug-commando-company",
    "ak-47-nouveau-rouge",
    "desert-eagle-mulberry",
    "m4a1-s-glitched-paint",
    "usp-s-bleeding-edge",
    "glock-18-coral-bloom",
    "awp-arsenic-spill",
    "p250-red-tide",
    "ssg-08-blush-pour",
    "mp9-shredded",
    "m4a1-s-rose-hex",
    "m4a4-steel-work",
    "p250-sedimentary",
    "galil-ar-o-ranger",
    "tec-9-citric-acid",
    "sg-553-basket-halftone",
    "famas-grey-ghost",
    "mac-10-bronzer",
    "mp7-short-ochre",
    "dual-berettas-bordeux",
    "scar-20-short-ochre",
    "five-seven-autumn-thicket",
    "cz75-auto-pink-pearl",
    "g3sg1-red-jasper",
    "xm1014-canvas-cloud",
    "nova-marsh-grass",
    "mp9-multi-terrain",
    "p90-desert-halftone",
    "pp-bizon-wood-block-camo",
    "dual-berettas-twin-turbo",
    "sg-553-integrale",
    "p250-vino-primo",
    "ak-47-safety-net",
    "mp7-fade",
    "ssg-08-hand-brake",
    "m4a4-converter",
    "usp-s-check-engine",
    "sawed-off-brake-light",
    "r8-revolver-nitro",
    "glock-18-high-beam",
    "mac-10-calf-skin",
    "pp-bizon-candy-apple",
    "mp9-slide",
    "mp5-sd-dirt-drop",
    "ump-45-mudder",
    "mag-7-rust-coat",
    "aug-sweeper",
    "m4a1-s-control-panel",
    "tec-9-remote-control",
    "glock-18-nuclear-garden",
    "mag-7-core-breach",
    "aug-random-access",
    "awp-acheron",
    "mp5-sd-co-processor",
    "p250-exchanger",
    "p90-facility-negative",
    "galil-ar-cold-fusion",
    "m4a4-mainframe",
    "negev-bulkhead",
    "mp7-motherboard",
    "pp-bizon-facility-sketch",
    "five-seven-coolant",
    "p250-facility-draft",
    "nova-mandrel",
    "ump-45-facility-dark",
    "ak-47-gold-arabesque",
    "ssg-08-death-strike",
    "ump-45-fade",
    "m4a4-red-ddpat",
    "usp-s-orange-anolis",
    "mac-10-case-hardened",
    "p250-black-tan",
    "galil-ar-amber-fade",
    "g3sg1-new-roots",
    "nova-quick-sand",
    "five-seven-withered-vine",
    "mp9-old-roots",
    "aug-spalted-wood",
    "m249-midnight-palm",
    "p90-desert-ddpat",
    "mp7-prey",
    "sg-553-bleached",
    "sawed-off-parched",
    "r8-revolver-desert-brush",
    "awp-desert-hydra",
    "desert-eagle-fennec-fox",
    "mp5-sd-oxide-oasis",
    "glock-18-pink-ddpat",
    "aug-sand-storm",
    "xm1014-elegant-vines",
    "usp-s-purple-ddpat",
    "sg-553-desert-blossom",
    "m249-humidor",
    "mp9-music-box",
    "p90-verdant-growth",
    "dual-berettas-drift-wood",
    "cz75-auto-midnight-palm",
    "famas-calicamo",
    "ssg-08-prey",
    "p250-drought",
    "mag-7-navy-sheen",
    "mac-10-sienna-damask",
    "pp-bizon-anolis",
    "m4a4-the-coalition",
    "glock-18-gamma-doppler",
    "usp-s-whiteout",
    "famas-meltdown",
    "mac-10-propaganda",
    "awp-pop-awp",
    "p2000-space-race",
    "nova-red-quartz",
    "cz75-auto-syndicate",
    "mp5-sd-autumn-twilly",
    "m4a1-s-fizzy-pop",
    "aug-amber-fade",
    "desert-eagle-sputnik",
    "r8-revolver-blaze",
    "tec-9-safety-net",
    "ssg-08-spring-twilly",
    "ump-45-full-stop",
    "m4a1-s-imminent-danger",
    "five-seven-fall-hazard",
    "sg-553-hazard-pay",
    "p250-digital-architect",
    "galil-ar-caution",
    "mag-7-prism-terrace",
    "ak-47-green-laminate",
    "p90-schematic",
    "nova-interlock",
    "negev-infrastructure",
    "ssg-08-carbon-fiber",
    "glock-18-red-tire",
    "pp-bizon-breaker-box",
    "ump-45-mechanism",
    "cz75-auto-framework",
    "famas-faulty-wiring",
    "mac-10-strats",
    "dual-berettas-oil-change",
    "xm1014-blue-tire",
    "famas-spitfire",
    "scar-20-emerald",
    "mag-7-hazard",
    "aug-anodized-navy",
    "pp-bizon-rust-coat",
    "glock-18-sand-dune",
    "sawed-off-mosaico",
    "ssg-08-mayan-dreams",
    "negev-palm",
    "p250-facets",
    "tec-9-tornado",
    "xm1014-jungle",
    "mp9-dry-season",
    "mp7-groundwater",
    "m249-jungle-ddpat",
    "five-seven-anodized-gunmetal",
    "m4a1-s-welcome-to-the-jungle",
    "ak-47-panthera-onca",
    "p90-run-and-hide",
    "xm1014-ancient-lore",
    "mac-10-gold-brick",
    "usp-s-ancient-visions",
    "galil-ar-dusk-ruins",
    "aug-carved-jade",
    "famas-dark-water",
    "tec-9-blast-from-the-past",
    "cz75-auto-silver",
    "mp7-tall-grass",
    "p2000-panther-camo",
    "g3sg1-ancient-ritual",
    "p90-ancient-earth",
    "sg-553-lush-ruins",
    "ssg-08-jungle-dashed",
    "r8-revolver-night",
    "nova-army-sheen",
    "m4a4-eye-of-horus",
    "famas-waters-of-nephthys",
    "p250-apep-s-curse",
    "glock-18-ramese-s-reach",
    "p90-scarab-rush",
    "nova-sobek-s-bite",
    "awp-black-nile",
    "ak-47-steel-delta",
    "tec-9-mummy-s-rot",
    "mag-7-copper-coated",
    "m4a1-s-mud-spec",
    "usp-s-desert-tactical",
    "ssg-08-azure-glyph",
    "mac-10-echoing-sands",
    "mp7-sunbaked",
    "xm1014-hieroglyph",
    "r8-revolver-inlay",
    "aug-snake-pit",
    "m249-submerged",
    "mp9-bulldozer",
    "glock-18-fade",
    "aug-hot-rod",
    "negev-anodized-navy",
    "five-seven-candy-apple",
    "ump-45-caramel",
    "sg-553-tornado",
    "tec-9-ossified",
    "ak-47-jungle-spray",
    "m4a4-jungle-tiger",
    "five-seven-jungle",
    "nova-forest-leaves",
    "ssg-08-lichen-dashed",
    "ak-47-jet-set",
    "ak-47-first-class",
    "desert-eagle-pilot",
    "sawed-off-first-class",
    "xm1014-red-leather",
    "usp-s-business-class",
    "mac-10-commuter",
    "p2000-coach-class",
    "p90-leather",
    "sg-553-traveler",
    "ssg-08-sand-dune",
    "g3sg1-contractor",
    "mp9-green-plaid",
    "cz75-auto-green-plaid",
    "mp7-olive-plaid",
    "p250-franklin",
    "ak-47-emerald-pinstripe",
    "desert-eagle-meteorite",
    "galil-ar-tuxedo",
    "cz75-auto-tuxedo",
    "mac-10-silver",
    "glock-18-death-rattle",
    "ump-45-carbon-fiber",
    "g3sg1-green-apple",
    "nova-caged-steel",
    "r8-revolver-bone-mask",
    "tec-9-urban-ddpat",
    "mp7-forest-ddpat",
    "sawed-off-forest-ddpat",
    "sg-553-army-sheen",
    "negev-army-sheen",
    "mp5-sd-lab-rats",
    "galil-ar-cerberus",
    "famas-styx",
    "glock-18-reactor",
    "mp9-setting-sun",
    "tec-9-toxic",
    "mac-10-nuclear-garden",
    "xm1014-bone-machine",
    "five-seven-hot-shot",
    "pp-bizon-chemical-green",
    "p250-contamination",
    "negev-nuclear-waste",
    "sg-553-fallout-warning",
    "aug-radiation-hazard",
    "awp-the-prince",
    "mag-7-cinquedea",
    "nova-baroque-orange",
    "mp9-stained-glass",
    "mac-10-red-filigree",
    "p90-baroque-red",
    "dual-berettas-emerald",
    "ssg-08-orange-filigree",
    "g3sg1-violet-murano",
    "ak-47-baroque-purple",
    "sg-553-candy-apple",
    "tec-9-orange-murano",
    "p250-dark-filigree",
    "cz75-auto-indigo",
    "negev-boroque-sand",
    "r8-revolver-canal-spray",
    "aug-navy-murano",
    "scar-20-stone-mosaico",
    "glock-18-twilight-galaxy",
    "m4a1-s-hot-rod",
    "dual-berettas-duelist",
    "sg-553-bulldozer",
    "p250-whiteout",
    "mac-10-fade",
    "cz75-auto-emerald",
    "mp7-full-stop",
    "five-seven-nitro",
    "desert-eagle-night",
    "usp-s-para-green",
    "galil-ar-urban-rubble",
    "scar-20-army-sheen",
    "cz75-auto-army-sheen",
    "mag-7-seabird",
    "m249-impact-drill",
    "awp-dragon-lore",
    "m4a1-s-knight",
    "desert-eagle-hand-cannon",
    "cz75-auto-chalice",
    "mp9-dark-age",
    "p2000-chainmail",
    "usp-s-royal-blue",
    "mag-7-silver",
    "nova-green-apple",
    "sawed-off-rust-coat",
    "mac-10-indigo",
    "p90-storm",
    "ump-45-indigo",
    "scar-20-storm",
    "dual-berettas-briar",
    "awp-fade",
    "m4a1-s-blue-phosphor",
    "usp-s-target-acquired",
    "five-seven-berries-and-cherries",
    "ump-45-crime-scene",
    "famas-prime-conspiracy",
    "m4a4-global-offensive",
    "scar-20-magna-carta",
    "ssg-08-threat-detected",
    "p2000-dispatch",
    "desert-eagle-the-bronze",
    "mp5-sd-nitro",
    "mag-7-carbon-fiber",
    "dual-berettas-switch-board",
    "p250-forest-night",
    "cz75-auto-jungle-dashed",
    "xm1014-charter",
    "mp9-army-sheen",
    "aug-surveillance",
    "r8-revolver-amber-fade",
    "p2000-amber-fade",
    "pp-bizon-brass",
    "m4a1-s-varicamo",
    "sg-553-damascus-steel",
    "ak-47-safari-mesh",
    "five-seven-orange-peel",
    "sawed-off-snake-camo",
    "mac-10-palm",
    "tec-9-varicamo",
    "p250-sand-dune",
    "mp9-sand-dashed",
    "g3sg1-desert-storm",
    "nova-predator",
    "p90-sand-spray",
    "scar-20-sand-mesh",
    "desert-eagle-blaze",
    "glock-18-brass",
    "p2000-scorpion",
    "awp-snake-camo",
    "sawed-off-copper",
    "aug-copperhead",
    "scar-20-palm",
    "ak-47-predator",
    "m4a4-desert-storm",
    "awp-medusa",
    "m4a4-poseidon",
    "m4a1-s-icarus-fell",
    "g3sg1-chronos",
    "mp9-pandora-s-box",
    "ump-45-minotaur-s-labyrinth",
    "awp-sun-in-leo",
    "tec-9-hades",
    "m249-shipping-forecast",
    "p2000-pathfinder",
    "nova-moon-in-libra",
    "dual-berettas-moon-in-libra",
    "aug-daedalus",
    "mp7-asterion",
    "ak-47-x-ray",
    "awp-silk-tiger",
    "mac-10-hot-snakes",
    "glock-18-franklin",
    "galil-ar-phoenix-blacklight",
    "sg-553-hypnotic",
    "desert-eagle-night-heist",
    "negev-phoenix-stencil",
    "p250-bengal-tiger",
    "p90-tiger-pit",
    "mp7-vault-heist",
    "nova-rust-coat",
    "ump-45-houndstooth",
    "r8-revolver-phoenix-marker",
    "pp-bizon-death-rattle",
    "sawed-off-clay-ambush",
    "tec-9-phoenix-chalk",
    "dual-berettas-heist",
    "m249-predator",
    "tec-9-brass",
    "dual-berettas-anodized-navy",
    "m4a4-tornado",
    "p250-gunsmoke",
    "mag-7-sand-dune",
    "nova-walnut",
    "awp-pit-viper",
    "glock-18-candy-apple",
    "mp7-anodized-navy",
    "sawed-off-full-stop",
    "xm1014-calicamo",
    "m4a1-s-boreal-forest",
    "ump-45-gunsmoke",
    "nova-candy-apple",
    "dual-berettas-stained",
    "p2000-granite-marbleized",
    "aug-contractor",
    "tec-9-groundwater",
    "nova-sand-dune",
    "pp-bizon-sand-dashed",
    "famas-colony",
    "dual-berettas-cobalt-quartz",
    "usp-s-night-ops",
    "sg-553-anodized-navy",
    "p90-teardown",
    "pp-bizon-night-ops",
    "awp-safari-mesh",
    "desert-eagle-mudder",
    "xm1014-blue-steel",
    "famas-cyanospatter",
    "g3sg1-jungle-dashed",
    "sg-553-waves-perforated",
    "xm1014-blue-spruce",
    "galil-ar-sage-spray",
    "p250-boreal-forest",
    "scar-20-splash-jam",
    "m4a4-modern-hunter",
    "p250-modern-hunter",
    "nova-blaze-orange",
    "xm1014-blaze-orange",
    "pp-bizon-modern-hunter",
    "nova-modern-hunter",
    "p2000-grassland-leaves",
    "mac-10-tornado",
    "xm1014-grassland",
    "pp-bizon-forest-leaves",
    "mag-7-bulldozer",
    "mp9-hot-rod",
    "ump-45-blaze",
    "mac-10-amber-fade",
    "glock-18-groundwater",
    "ssg-08-tropical-storm",
    "mp7-orange-peel",
    "sg-553-gator-mesh",
    "negev-calicamo",
    "five-seven-contractor",
    "p90-scorched",
    "aug-colony",
    "g3sg1-safari-mesh",
    "p250-bone-mask",
    "galil-ar-hunting-blind",
    "awp-gungnir",
    "negev-mj-lnir",
    "aug-flame-j-rmungandr",
    "p90-astral-j-rmungandr",
    "desert-eagle-emerald-j-rmungandr",
    "mac-10-copper-borre",
    "scar-20-brass",
    "xm1014-frost-borre",
    "cz75-auto-emerald-quartz",
    "m4a1-s-moss-quartz",
    "dual-berettas-pyre",
    "usp-s-pathfinder",
    "mag-7-chainmail",
    "ssg-08-red-stone",
    "galil-ar-tornado",
    "mp7-scorched",
    "famas-night-borre",
    "sg-553-barricade",
    "tec-9-nuclear-threat",
    "p250-nuclear-threat",
    "m4a4-radiation-hazard",
    "xm1014-fallout-warning",
    "p90-fallout-warning",
    "ump-45-fallout-warning",
    "sawed-off-irradiated-alert",
    "pp-bizon-irradiated-alert",
    "mag-7-irradiated-alert",
    "mp7-whiteout",
    "p2000-silver",
    "g3sg1-arctic-camo",
    "galil-ar-winter-forest",
    "m249-blizzard-marbleized",
    "famas-contrast-spray",
    "m4a1-s-master-piece",
    "awp-pink-ddpat",
    "usp-s-road-rash",
    "cz75-auto-nitro",
    "ssg-08-detour",
    "xm1014-varicamo-blue",
    "glock-18-night",
    "desert-eagle-urban-ddpat",
    "p2000-grassland",
    "mp7-gunsmoke",
    "mp9-storm",
    "mag-7-storm",
    "sawed-off-sage-spray",
    "m249-contrast-spray",
    "ump-45-scorched",
    "aug-akihabara-accept",
    "ak-47-hydroponic",
    "desert-eagle-sunset-storm-1",
    "m4a4-daybreak",
    "five-seven-neon-kimono",
    "desert-eagle-sunset-storm-2",
    "tec-9-terrace",
    "galil-ar-aqua-terrace",
    "mag-7-counter-terrace",
    "desert-eagle-midnight-storm",
    "p250-crimson-kimono",
    "tec-9-bamboo-forest",
    "pp-bizon-bamboo-print",
    "p250-mint-kimono",
    "g3sg1-orange-kimono",
    "sawed-off-bamboo-shadow",
    "m4a1-s-nitro",
    "ssg-08-acid-fade",
    "famas-teardown",
    "five-seven-silver-quartz",
    "g3sg1-varicamo",
    "m249-gator-mesh",
    "galil-ar-varicamo",
    "aug-condemned",
    "usp-s-forest-leaves",
    "mp9-orange-peel",
    "tec-9-army-mesh",
    "ssg-08-blue-spruce",
    "mp7-army-recon",
    "dual-berettas-contractor",
    "scar-20-contractor",
    "ak-47-wild-lotus",
    "mp9-wild-lily",
    "aug-midnight-lily",
    "glock-18-synth-leaf",
    "p250-metallic-ddpat",
    "mac-10-candy-apple",
    "mag-7-metallic-ddpat",
    "p90-ash-wood",
    "scar-20-carbon-fiber",
    "nova-polar-mesh",
    "g3sg1-polar-camo",
    "five-seven-forest-night",
    "ump-45-urban-ddpat",
    "dual-berettas-colony",
    "pp-bizon-urban-dashed",
    "dual-berettas-demolition",
    "ak-47-black-laminate",
    "p90-glacier-mesh",
    "pp-bizon-carbon-fiber",
    "mac-10-urban-ddpat",
    "xm1014-urban-perforated",
    "m4a4-howl",
    "usp-s-orion",
    "mac-10-curse",
    "cz75-auto-poison-dart",
    "dual-berettas-retribution",
    "p90-desert-warfare"
}

def normalize_name(name):
    # Remove | and extra spaces, convert to lower case, replace spaces with hyphens
    name = name.replace("|", "").strip()
    # Remove multiple spaces
    name = re.sub(r'\s+', ' ', name)
    return name.lower().replace(" ", "-")

def get_case_name_from_url(url):
    path = urlparse(url).path
    # Example: /case/422/Fever-Case
    parts = path.split('/')
    if parts:
        return parts[-1].lower()
    return ""

import shutil

def download_image(url, filename, folder="images"):
    if not os.path.exists(folder):
        os.makedirs(folder)
    
    dest_path = os.path.join(folder, filename)
    if os.path.exists(dest_path):
        print(f"Skipping {filename}, already exists.")
        return

    # Check if it's a local file (from saved HTML)
    if os.path.exists(url):
        try:
            shutil.copy(url, dest_path)
            print(f"Copied local file to {filename}")
            return
        except Exception as e:
            print(f"Error copying local file {url}: {e}")
            return

    # Otherwise try downloading
    try:
        headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
        }
        response = requests.get(url, headers=headers)
        if response.status_code == 200:
            with open(dest_path, 'wb') as f:
                f.write(response.content)
            print(f"Downloaded {filename}")
        else:
            print(f"Failed to download {url}: Status {response.status_code}")
    except Exception as e:
        print(f"Error downloading {url}: {e}")

def process_source(source):
    html = ""
    case_name = ""
    
    if os.path.isfile(source):
        print(f"Reading from file: {source}")
        with open(source, 'r', encoding='utf-8') as f:
            html = f.read()
        
        # Derive case name from filename
        base = os.path.splitext(os.path.basename(source))[0]
        # Remove common suffix from "Save As"
        base = base.replace(" Skins - CS2 Skins", "")
        # Normalize and handle underscores
        case_name = normalize_name(base).replace("_", "-")
    else:
        print(f"Processing URL: {source}")
        case_name = get_case_name_from_url(source)

        headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "Accept-Language": "en-US,en;q=0.9",
            "Referer": "https://stash.clash.gg/",
            "Upgrade-Insecure-Requests": "1"
        }
        
        try:
            response = requests.get(source, headers=headers)
            response.raise_for_status()
            html = response.text
        except Exception as e:
            print(f"Failed to fetch page: {e}")
            print("Tip: If you get a 403 Forbidden error, the site is protected. Save the page as HTML (e.g., 'fever-case.html') and run the script on that file.")
            return

    print(f"Case name derived: {case_name}")

    # Regex to find images with alt text
    # <img class="..." src="..." alt="...">
    # We look for src and alt attributes. Order might vary, so we scan for img tags first.
    
    img_tags = re.findall(r'<img[^>]+>', html)
    
    for tag in img_tags:
        # Extract src
        src_match = re.search(r'src="([^"]+)"', tag)
        # Extract alt
        alt_match = re.search(r'alt="([^"]+)"', tag)
        
        if src_match and alt_match:
            src = html_module.unescape(src_match.group(1))
            alt = html_module.unescape(alt_match.group(1))
            
            # Filter: Only keep images with '512fx384f' or 'light_large' in the URL
            if "512fx384f" not in src and "light_large" not in src:
                # print(f"Skipping {alt} - URL does not contain 512fx384f or light_large")
                continue

            # Skip if alt is empty or generic
            if not alt or alt.lower() == "image":
                continue

            normalized = normalize_name(alt)
            
            # Candidates
            # User requested to use just the slug name without the case suffix
            found_slug = normalized
            
            if found_slug:
                print(f"Processing: '{alt}' -> {found_slug} (High Res)")
                # Check if src is a valid URL
                if src.startswith("//"):
                    src = "https:" + src
                elif src.startswith("/"):
                    src = "https://stash.clash.gg" + src # Assuming base
                
                download_image(src, f"{found_slug}.png", folder=r"C:\Users\jojon\Desktop\csinvest\csinvest-frontend\src\assets\skins")
            else:
                # print(f"No match for '{alt}' (Normalized: {normalized})")
                pass

import glob

if __name__ == "__main__":
    # Process all HTML files in the current directory
    html_files = glob.glob("*.html")
    
    if not html_files:
        print("No HTML files found in the current directory.")
    else:
        print(f"Found {len(html_files)} HTML files to process.")
        for f in html_files:
            process_source(f)
