import requests
import re
import os
import html as html_module
from urllib.parse import urlparse

# List of slugs provided by the user
SLUGS = {
    "sealed-genesis-terminal",
    "kilowatt-case",
    "revolution-case",
    "dreams-nightmares-case",
    "operation-riptide-case",
    "snakebite-case",
    "operation-broken-fang-case",
    "fracture-case",
    "prisma-2-case",
    "cs20-case",
    "shattered-web-case",
    "prisma-case",
    "danger-zone-case",
    "fever-case",
    "recoil-case",
    "gallery-case",
    "horizon-case",
    "clutch-case",
    "spectrum-2-case",
    "operation-hydra-case",
    "spectrum-case",
    "glove-case",
    "gamma-2-case",
    "gamma-case",
    "operation-wildfire-case",
    "revolver-case",
    "shadow-case",
    "falchion-case",
    "chroma-case",
    "operation-vanguard-weapon-case",
    "esports-2014-summer-case",
    "operation-breakout-weapon-case",
    "huntsman-weapon-case",
    "operation-phoenix-weapon-case",
    "cs-go-weapon-case-3",
    "winter-offensive-weapon-case",
    "esports-2013-winter-case",
    "cs-go-weapon-case-2",
    "operation-bravo-case",
    "esports-2013-case",
    "cs-go-weapon-case",
    "chroma-3-case",
    "ak-47-head-shot",
    "m4a4-temukau",
    "p2000-wicked-sick",
    "ump-45-wild-child",
    "awp-duality",
    "m4a1-s-emphorosaur-s",
    "glock-18-umbral-rabbit",
    "p90-neoqueen",
    "r8-revolver-banana-cannon",
    "mac-10-sakkaku",
    "mag-7-insomnia",
    "mp9-featherweight",
    "scar-20-fragments",
    "p250-re-built",
    "mp5-sd-liquidation",
    "sg-553-cyberforce",
    "tec-9-rebel",
    "sport-gloves-vice-revolution-case",
    "driver-gloves-imperial-plaid-revolution-case",
    "moto-gloves-polygon-revolution-case",
    "sport-gloves-omega-revolution-case",
    "hand-wraps-overprint-revolution-case",
    "driver-gloves-racing-green-revolution-case",
    "sport-gloves-bronze-morph-revolution-case",
    "hand-wraps-cobalt-skulls-revolution-case",
    "hydra-gloves-emerald-revolution-case",
    "hydra-gloves-mangrove-revolution-case",
    "moto-gloves-transport-revolution-case",
    "hydra-gloves-case-hardened-revolution-case",
    "driver-gloves-overtake-revolution-case",
    "sport-gloves-amphibious-revolution-case",
    "moto-gloves-turtle-revolution-case",
    "specialist-gloves-mogul-revolution-case",
    "hand-wraps-duct-tape-revolution-case",
    "driver-gloves-king-snake-revolution-case",
    "hydra-gloves-rattler-revolution-case",
    "specialist-gloves-buckshot-revolution-case",
    "specialist-gloves-fade-revolution-case",
    "specialist-gloves-crimson-web-revolution-case",
    "hand-wraps-arboreal-revolution-case",
    "moto-gloves-pow-revolution-case",
    "famas-bad-trip",
    "awp-printstream",
    "ak-47-searing-rage",
    "glock-18-shinobu",
    "ump-45-k-o-factory",
    "desert-eagle-serpent-strike",
    "zeus-x27-tosai",
    "galil-ar-control",
    "p90-wave-breaker",
    "nova-rising-sun",
    "usp-s-pc-grn",
    "m4a4-choppa",
    "ssg-08-memorial",
    "mp9-nexus",
    "p2000-sure-grip",
    "xm1014-mockingbird",
    "mag-7-resupply",
    "skeleton-knife-tiger-tooth-fever-case",
    "skeleton-knife-damascus-steel-fever-case",
    "skeleton-knife-ultraviolet-fever-case",
    "skeleton-knife-marble-fade-fever-case",
    "skeleton-knife-doppler-fever-case",
    "skeleton-knife-rust-coat-fever-case",
    "survival-knife-tiger-tooth-fever-case",
    "survival-knife-doppler-fever-case",
    "survival-knife-ultraviolet-fever-case",
    "survival-knife-damascus-steel-fever-case",
    "survival-knife-rust-coat-fever-case",
    "survival-knife-marble-fade-fever-case",
    "paracord-knife-doppler-fever-case",
    "paracord-knife-tiger-tooth-fever-case",
    "paracord-knife-marble-fade-fever-case",
    "paracord-knife-damascus-steel-fever-case",
    "paracord-knife-rust-coat-fever-case",
    "paracord-knife-ultraviolet-fever-case",
    "nomad-knife-ultraviolet-fever-case",
    "nomad-knife-marble-fade-fever-case",
    "nomad-knife-doppler-fever-case",
    "nomad-knife-tiger-tooth-fever-case",
    "nomad-knife-damascus-steel-fever-case",
    "nomad-knife-rust-coat-fever-case",
    "desert-eagle-printstream-fracture-case",
    "ak-47-legion-of-anubis-fracture-case",
    "m4a4-tooth-fairy-fracture-case",
    "glock-18-vogue-fracture-case",
    "xm1014-entombed-fracture-case",
    "mag-7-monster-call-fracture-case",
    "mac-10-allure-fracture-case",
    "tec-9-brother-fracture-case",
    "galil-ar-connexion-fracture-case",
    "mp5-sd-kitbash-fracture-case",
    "ssg-08-mainframe-001-fracture-case",
    "pp-bizon-runic-fracture-case",
    "p2000-gnarled-fracture-case",
    "p90-freight-fracture-case",
    "p250-cassette-fracture-case",
    "negev-ultralight-fracture-case",
    "sg-553-ol-rusty-fracture-case",
    "skeleton-knife-slaughter-fracture-case",
    "skeleton-knife-vanilla-fracture-case",
    "skeleton-knife-stained-fracture-case",
    "skeleton-knife-crimson-web-fracture-case",
    "skeleton-knife-case-hardened-fracture-case",
    "skeleton-knife-fade-fracture-case",
    "skeleton-knife-blue-steel-fracture-case",
    "skeleton-knife-night-stripe-fracture-case",
    "skeleton-knife-urban-masked-fracture-case",
    "skeleton-knife-forest-ddpat-fracture-case",
    "skeleton-knife-boreal-forest-fracture-case",
    "skeleton-knife-safari-mesh-fracture-case",
    "skeleton-knife-scorched-fracture-case",
    "nomad-knife-slaughter-fracture-case",
    "nomad-knife-vanilla-fracture-case",
    "nomad-knife-stained-fracture-case",
    "nomad-knife-crimson-web-fracture-case",
    "nomad-knife-case-hardened-fracture-case",
    "nomad-knife-fade-fracture-case",
    "nomad-knife-blue-steel-fracture-case",
    "nomad-knife-night-stripe-fracture-case",
    "nomad-knife-urban-masked-fracture-case",
    "nomad-knife-forest-ddpat-fracture-case",
    "nomad-knife-boreal-forest-fracture-case",
    "nomad-knife-safari-mesh-fracture-case",
    "nomad-knife-scorched-fracture-case",
    "survival-knife-slaughter-fracture-case",
    "survival-knife-vanilla-fracture-case",
    "survival-knife-stained-fracture-case",
    "survival-knife-crimson-web-fracture-case",
    "survival-knife-case-hardened-fracture-case",
    "survival-knife-fade-fracture-case",
    "survival-knife-blue-steel-fracture-case",
    "survival-knife-night-stripe-fracture-case",
    "survival-knife-urban-masked-fracture-case",
    "survival-knife-forest-ddpat-fracture-case",
    "survival-knife-boreal-forest-fracture-case",
    "survival-knife-safari-mesh-fracture-case",
    "survival-knife-scorched-fracture-case",
    "paracord-knife-slaughter-fracture-case",
    "paracord-knife-vanilla-fracture-case",
    "paracord-knife-stained-fracture-case",
    "paracord-knife-crimson-web-fracture-case",
    "paracord-knife-case-hardened-fracture-case",
    "paracord-knife-fade-fracture-case",
    "paracord-knife-blue-steel-fracture-case",
    "paracord-knife-night-stripe-fracture-case",
    "paracord-knife-urban-masked-fracture-case",
    "paracord-knife-forest-ddpat-fracture-case",
    "paracord-knife-boreal-forest-fracture-case",
    "paracord-knife-safari-mesh-fracture-case",
    "paracord-knife-scorched-fracture-case",
    "m4a1-s-vaporwave",
    "glock-18-gold-toof",
    "ak-47-the-outsiders",
    "p250-epicenter",
    "ump-45-neo-noir",
    "m4a4-turbine",
    "mac-10-saib-oni",
    "ssg-08-rapid-transit",
    "dual-berettas-hydro-strike",
    "p90-randy-rush",
    "desert-eagle-calligraffiti",
    "usp-s-27",
    "aug-luxe-trim",
    "r8-revolver-tango",
    "mp5-sd-statics",
    "scar-20-trail-blazer",
    "m249-hypnosis",
    "kukri-knife-slaughter-gallery-case",
    "kukri-knife-case-hardened-gallery-case",
    "kukri-knife-blue-steel-gallery-case",
    "kukri-knife-stained-gallery-case",
    "kukri-knife-scorched-gallery-case",
    "kukri-knife-fade-gallery-case",
    "kukri-knife-safari-mesh-gallery-case",
    "kukri-knife-boreal-forest-gallery-case",
    "kukri-knife-urban-masked-gallery-case",
    "kukri-knife-night-stripe-gallery-case",
    "kukri-knife-crimson-web-gallery-case",
    "kukri-knife-vanilla-gallery-case",
    "kukri-knife-forest-ddpat-gallery-case",
    "ak-47-the-oligarch",
    "m4a4-full-throttle",
    "awp-ice-coaled",
    "mp7-smoking-kills",
    "glock-18-mirror-mosaic",
    "m4a1-s-liquidation",
    "ump-45-continuum",
    "mac-10-cat-fight",
    "dual-berettas-angel-eyes",
    "nova-ocular",
    "p2000-red-wing",
    "p250-bullfrog",
    "mp5-sd-focus",
    "aug-trigger-discipline",
    "mp9-broken-record",
    "scar-20-caged",
    "mag-7-magnitude",
    "ak-47-inheritance-kilowatt-case",
    "awp-chrome-cannon-kilowatt-case",
    "m4a1-s-black-lotus-kilowatt-case",
    "usp-s-jawbreaker-kilowatt-case",
    "zeus-x27-olympus-kilowatt-case",
    "m4a4-etch-lord-kilowatt-case",
    "glock-18-block-18-kilowatt-case",
    "mp7-just-smile-kilowatt-case",
    "sawed-off-analog-input-kilowatt-case",
    "five-seven-hybrid-kilowatt-case",
    "mac-10-light-box-kilowatt-case",
    "tec-9-slag-kilowatt-case",
    "nova-dark-sigil-kilowatt-case",
    "ssg-08-dezastre-kilowatt-case",
    "dual-berettas-hideout-kilowatt-case",
    "ump-45-motorized-kilowatt-case",
    "xm1014-irezumi-kilowatt-case",
    "kukri-knife-slaughter-kilowatt-case",
    "kukri-knife-case-hardened-kilowatt-case",
    "kukri-knife-blue-steel-kilowatt-case",
    "kukri-knife-stained-kilowatt-case",
    "kukri-knife-scorched-kilowatt-case",
    "kukri-knife-fade-kilowatt-case",
    "kukri-knife-safari-mesh-kilowatt-case",
    "kukri-knife-boreal-forest-kilowatt-case",
    "kukri-knife-urban-masked-kilowatt-case",
    "kukri-knife-night-stripe-kilowatt-case",
    "kukri-knife-crimson-web-kilowatt-case",
    "kukri-knife-vanilla-kilowatt-case",
    "kukri-knife-forest-ddpat-kilowatt-case",
    "awp-chromatic-aberration",
    "usp-s-printstream",
    "ak-47-ice-coaled",
    "sawed-off-kiss-love",
    "p250-visions",
    "dual-berettas-flora-carnivora",
    "sg-553-dragon-tech",
    "r8-revolver-crazy-8",
    "p90-vent-rush",
    "m249-downtown",
    "glock-18-winterized",
    "m4a4-poly-mag",
    "famas-meow-36",
    "galil-ar-destroyer",
    "mac-10-monkeyflage",
    "ump-45-roadblock",
    "negev-drop-me",
    "mp9-starlight-protector",
    "ak-47-nightwish",
    "mp7-abyssal-apparition",
    "famas-rapid-eye-movement",
    "dual-berettas-melondrama",
    "m4a1-s-night-terror",
    "usp-s-ticket-to-hell",
    "pp-bizon-space-cat",
    "xm1014-zombie-offensive",
    "g3sg1-dream-glade",
    "five-seven-scrawl",
    "scar-20-poultrygeist",
    "mac-10-ensnared",
    "mp5-sd-necro-jr",
    "mag-7-foresight",
    "sawed-off-spirit-board",
    "p2000-lifted-spirits",
    "butterfly-knife-bright-water-dreams-nightmares-case",
    "famas-valence",
    "butterfly-knife-autotronic-dreams-nightmares-case",
    "butterfly-knife-freehand-dreams-nightmares-case",
    "butterfly-knife-lore-dreams-nightmares-case",
    "butterfly-knife-black-laminate-dreams-nightmares-case",
    "butterfly-knife-gamma-doppler-dreams-nightmares-case",
    "falchion-knife-gamma-doppler-dreams-nightmares-case",
    "falchion-knife-lore-dreams-nightmares-case",
    "falchion-knife-bright-water-dreams-nightmares-case",
    "falchion-knife-freehand-dreams-nightmares-case",
    "falchion-knife-autotronic-dreams-nightmares-case",
    "falchion-knife-black-laminate-dreams-nightmares-case",
    "bowie-knife-gamma-doppler-dreams-nightmares-case",
    "bowie-knife-lore-dreams-nightmares-case",
    "bowie-knife-freehand-dreams-nightmares-case",
    "bowie-knife-autotronic-dreams-nightmares-case",
    "bowie-knife-bright-water-dreams-nightmares-case",
    "bowie-knife-black-laminate-dreams-nightmares-case",
    "shadow-daggers-gamma-doppler-dreams-nightmares-case",
    "shadow-daggers-lore-dreams-nightmares-case",
    "shadow-daggers-freehand-dreams-nightmares-case",
    "shadow-daggers-bright-water-dreams-nightmares-case",
    "shadow-daggers-black-laminate-dreams-nightmares-case",
    "shadow-daggers-autotronic-dreams-nightmares-case",
    "huntsman-knife-autotronic-dreams-nightmares-case",
    "huntsman-knife-gamma-doppler-dreams-nightmares-case",
    "huntsman-knife-lore-dreams-nightmares-case",
    "huntsman-knife-freehand-dreams-nightmares-case",
    "huntsman-knife-bright-water-dreams-nightmares-case",
    "huntsman-knife-black-laminate-dreams-nightmares-case",
    "ak-47-leet-museo",
    "desert-eagle-ocean-drive",
    "ssg-08-turbo-peek",
    "glock-18-snack-attack",
    "mac-10-toybox",
    "m4a4-spider-lily",
    "mp9-mount-fuji",
    "famas-zx-spectron",
    "five-seven-boost-protocol",
    "mag-7-bi83-spectrum",
    "usp-s-black-lotus",
    "xm1014-watchdog",
    "aug-plague",
    "pp-bizon-lumen",
    "g3sg1-keeping-tabs",
    "dual-berettas-tread",
    "mp7-guerrilla",
    "butterfly-knife-bright-water-operation-riptide-case",
    "butterfly-knife-autotronic-operation-riptide-case",
    "butterfly-knife-freehand-operation-riptide-case",
    "butterfly-knife-lore-operation-riptide-case",
    "butterfly-knife-black-laminate-operation-riptide-case",
    "butterfly-knife-gamma-doppler-operation-riptide-case",
    "falchion-knife-gamma-doppler-operation-riptide-case",
    "falchion-knife-lore-operation-riptide-case",
    "falchion-knife-bright-water-operation-riptide-case",
    "falchion-knife-freehand-operation-riptide-case",
    "falchion-knife-autotronic-operation-riptide-case",
    "falchion-knife-black-laminate-operation-riptide-case",
    "bowie-knife-gamma-doppler-operation-riptide-case",
    "bowie-knife-lore-operation-riptide-case",
    "bowie-knife-freehand-operation-riptide-case",
    "bowie-knife-autotronic-operation-riptide-case",
    "bowie-knife-bright-water-operation-riptide-case",
    "bowie-knife-black-laminate-operation-riptide-case",
    "shadow-daggers-gamma-doppler-operation-riptide-case",
    "shadow-daggers-lore-operation-riptide-case",
    "shadow-daggers-freehand-operation-riptide-case",
    "shadow-daggers-bright-water-operation-riptide-case",
    "shadow-daggers-black-laminate-operation-riptide-case",
    "shadow-daggers-autotronic-operation-riptide-case",
    "huntsman-knife-autotronic-operation-riptide-case",
    "huntsman-knife-gamma-doppler-operation-riptide-case",
    "huntsman-knife-lore-operation-riptide-case",
    "huntsman-knife-freehand-operation-riptide-case",
    "huntsman-knife-bright-water-operation-riptide-case",
    "huntsman-knife-black-laminate-operation-riptide-case",
    "glock-18-bullet-queen",
    "m4a1-s-player-two",
    "ak-47-phantom-disruptor",
    "mac-10-disco-tech",
    "mag-7-justice",
    "ssg-08-fever-dream",
    "sg-553-darkwing",
    "p2000-acid-etched",
    "sawed-off-apocalypto",
    "scar-20-enforcer",
    "awp-capillary",
    "desert-eagle-blue-ply",
    "aug-tom-cat",
    "negev-prototype",
    "mp5-sd-desert-strike",
    "cz75-auto-distressed",
    "r8-revolver-bone-forged",
    "talon-knife-marble-fade-prisma-2-case",
    "talon-knife-ultraviolet-prisma-2-case",
    "talon-knife-damascus-steel-prisma-2-case",
    "talon-knife-tiger-tooth-prisma-2-case",
    "talon-knife-rust-coat-prisma-2-case",
    "talon-knife-doppler-prisma-2-case",
    "stiletto-knife-ultraviolet-prisma-2-case",
    "stiletto-knife-rust-coat-prisma-2-case",
    "stiletto-knife-damascus-steel-prisma-2-case",
    "stiletto-knife-marble-fade-prisma-2-case",
    "stiletto-knife-tiger-tooth-prisma-2-case",
    "stiletto-knife-doppler-prisma-2-case",
    "ursus-knife-doppler-prisma-2-case",
    "ursus-knife-tiger-tooth-prisma-2-case",
    "ursus-knife-damascus-steel-prisma-2-case",
    "ursus-knife-ultraviolet-prisma-2-case",
    "ursus-knife-rust-coat-prisma-2-case",
    "ursus-knife-marble-fade-prisma-2-case",
    "navaja-knife-ultraviolet-prisma-2-case",
    "navaja-knife-doppler-prisma-2-case",
    "navaja-knife-rust-coat-prisma-2-case",
    "navaja-knife-marble-fade-prisma-2-case",
    "navaja-knife-tiger-tooth-prisma-2-case",
    "navaja-knife-damascus-steel-prisma-2-case",
    "awp-containment-breach-shattered-web-case",
    "mac-10-stalker-shattered-web-case",
    "tec-9-decimator-shattered-web-case",
    "ssg-08-bloodshot-shattered-web-case",
    "sg-553-colony-iv-shattered-web-case",
    "ak-47-rat-rod-shattered-web-case",
    "aug-arctic-wolf-shattered-web-case",
    "mp7-neon-ply-shattered-web-case",
    "p2000-obsidian-shattered-web-case",
    "pp-bizon-embargo-shattered-web-case",
    "dual-berettas-balance-shattered-web-case",
    "mp5-sd-acid-wash-shattered-web-case",
    "r8-revolver-memento-shattered-web-case",
    "g3sg1-black-sand-shattered-web-case",
    "nova-plume-shattered-web-case",
    "scar-20-torn-shattered-web-case",
    "m249-warbird-shattered-web-case",
    "skeleton-knife-slaughter-shattered-web-case",
    "skeleton-knife-vanilla-shattered-web-case",
    "skeleton-knife-stained-shattered-web-case",
    "skeleton-knife-crimson-web-shattered-web-case",
    "skeleton-knife-case-hardened-shattered-web-case",
    "skeleton-knife-fade-shattered-web-case",
    "skeleton-knife-blue-steel-shattered-web-case",
    "skeleton-knife-night-stripe-shattered-web-case",
    "skeleton-knife-urban-masked-shattered-web-case",
    "skeleton-knife-forest-ddpat-shattered-web-case",
    "skeleton-knife-boreal-forest-shattered-web-case",
    "skeleton-knife-safari-mesh-shattered-web-case",
    "skeleton-knife-scorched-shattered-web-case",
    "nomad-knife-slaughter-shattered-web-case",
    "nomad-knife-vanilla-shattered-web-case",
    "nomad-knife-stained-shattered-web-case",
    "nomad-knife-crimson-web-shattered-web-case",
    "nomad-knife-case-hardened-shattered-web-case",
    "nomad-knife-fade-shattered-web-case",
    "nomad-knife-blue-steel-shattered-web-case",
    "nomad-knife-night-stripe-shattered-web-case",
    "nomad-knife-urban-masked-shattered-web-case",
    "nomad-knife-forest-ddpat-shattered-web-case",
    "nomad-knife-boreal-forest-shattered-web-case",
    "nomad-knife-safari-mesh-shattered-web-case",
    "nomad-knife-scorched-shattered-web-case",
    "survival-knife-slaughter-shattered-web-case",
    "survival-knife-vanilla-shattered-web-case",
    "survival-knife-stained-shattered-web-case",
    "survival-knife-crimson-web-shattered-web-case",
    "survival-knife-case-hardened-shattered-web-case",
    "survival-knife-fade-shattered-web-case",
    "survival-knife-blue-steel-shattered-web-case",
    "survival-knife-night-stripe-shattered-web-case",
    "survival-knife-urban-masked-shattered-web-case",
    "survival-knife-forest-ddpat-shattered-web-case",
    "survival-knife-boreal-forest-shattered-web-case",
    "survival-knife-safari-mesh-shattered-web-case",
    "survival-knife-scorched-shattered-web-case",
    "paracord-knife-slaughter-shattered-web-case",
    "paracord-knife-vanilla-shattered-web-case",
    "paracord-knife-stained-shattered-web-case",
    "paracord-knife-crimson-web-shattered-web-case",
    "paracord-knife-case-hardened-shattered-web-case",
    "paracord-knife-fade-shattered-web-case",
    "paracord-knife-blue-steel-shattered-web-case",
    "paracord-knife-night-stripe-shattered-web-case",
    "paracord-knife-urban-masked-shattered-web-case",
    "paracord-knife-forest-ddpat-shattered-web-case",
    "paracord-knife-boreal-forest-shattered-web-case",
    "paracord-knife-safari-mesh-shattered-web-case",
    "paracord-knife-scorched-shattered-web-case",
    "awp-wildfire",
    "famas-commemoration",
    "mp9-hydra",
    "p90-nostalgia",
    "aug-death-by-puppy",
    "mp5-sd-agent",
    "five-seven-buddy",
    "p250-inferno",
    "m249-aztec",
    "ump-45-plastique",
    "glock-18-sacrifice",
    "famas-decommissioned",
    "scar-20-assault",
    "dual-berettas-elite-1-6",
    "tec-9-flash-out",
    "mac-10-classic-crate",
    "mag-7-popdog",
    "classic-knife-night-stripe",
    "classic-knife-urban-masked",
    "classic-knife-slaughter",
    "classic-knife-vanilla",
    "classic-knife-case-hardened",
    "classic-knife-blue-steel",
    "classic-knife-safari-mesh",
    "classic-knife-forest-ddpat",
    "classic-knife-crimson-web",
    "classic-knife-scorched",
    "classic-knife-stained",
    "classic-knife-boreal-forest",
    "classic-knife-fade",
    "five-seven-angry-mob",
    "m4a4-the-emperor",
    "aug-momentum",
    "r8-revolver-skull-crusher",
    "xm1014-incinegator",
    "awp-atheris",
    "desert-eagle-light-rail",
    "tec-9-bamboozle",
    "ump-45-moonrise",
    "mp5-sd-gauss",
    "ak-47-uncharted",
    "famas-crypsis",
    "galil-ar-akoben",
    "mp7-mischief",
    "p90-off-world",
    "mac-10-whitefish",
    "p250-verdigris",
    "talon-knife-marble-fade-prisma-case",
    "talon-knife-ultraviolet-prisma-case",
    "talon-knife-damascus-steel-prisma-case",
    "talon-knife-tiger-tooth-prisma-case",
    "talon-knife-rust-coat-prisma-case",
    "talon-knife-doppler-prisma-case",
    "stiletto-knife-ultraviolet-prisma-case",
    "stiletto-knife-rust-coat-prisma-case",
    "stiletto-knife-damascus-steel-prisma-case",
    "stiletto-knife-marble-fade-prisma-case",
    "stiletto-knife-tiger-tooth-prisma-case",
    "stiletto-knife-doppler-prisma-case",
    "ursus-knife-doppler-prisma-case",
    "ursus-knife-tiger-tooth-prisma-case",
    "ursus-knife-damascus-steel-prisma-case",
    "ursus-knife-ultraviolet-prisma-case",
    "ursus-knife-rust-coat-prisma-case",
    "ursus-knife-marble-fade-prisma-case",
    "navaja-knife-ultraviolet-prisma-case",
    "navaja-knife-doppler-prisma-case",
    "navaja-knife-rust-coat-prisma-case",
    "navaja-knife-marble-fade-prisma-case",
    "navaja-knife-tiger-tooth-prisma-case",
    "navaja-knife-damascus-steel-prisma-case",
    "ak-47-asiimov",
    "awp-neo-noir",
    "desert-eagle-mecha-industries",
    "mp5-sd-phosphor",
    "ump-45-momentum",
    "usp-s-flashback",
    "p250-nevermore",
    "galil-ar-signal",
    "g3sg1-scavenger",
    "mac-10-pipe-down",
    "m4a4-magnesium",
    "glock-18-oxide-blaze",
    "tec-9-fubar",
    "nova-wood-fired",
    "mp9-modest-threat",
    "sg-553-danger-close",
    "sawed-off-black-sand",
    "talon-knife-case-hardened-danger-zone-case",
    "talon-knife-fade-danger-zone-case",
    "talon-knife-stained-danger-zone-case",
    "talon-knife-blue-steel-danger-zone-case",
    "talon-knife-boreal-forest-danger-zone-case",
    "talon-knife-safari-mesh-danger-zone-case",
    "talon-knife-night-stripe-danger-zone-case",
    "talon-knife-forest-ddpat-danger-zone-case",
    "talon-knife-vanilla-danger-zone-case",
    "talon-knife-scorched-danger-zone-case",
    "talon-knife-slaughter-danger-zone-case",
    "talon-knife-crimson-web-danger-zone-case",
    "talon-knife-urban-masked-danger-zone-case",
    "stiletto-knife-crimson-web-danger-zone-case",
    "stiletto-knife-vanilla-danger-zone-case",
    "stiletto-knife-case-hardened-danger-zone-case",
    "stiletto-knife-fade-danger-zone-case",
    "stiletto-knife-stained-danger-zone-case",
    "stiletto-knife-blue-steel-danger-zone-case",
    "stiletto-knife-boreal-forest-danger-zone-case",
    "stiletto-knife-safari-mesh-danger-zone-case",
    "stiletto-knife-night-stripe-danger-zone-case",
    "stiletto-knife-forest-ddpat-danger-zone-case",
    "stiletto-knife-scorched-danger-zone-case",
    "stiletto-knife-slaughter-danger-zone-case",
    "stiletto-knife-urban-masked-danger-zone-case",
    "ursus-knife-slaughter-danger-zone-case",
    "ursus-knife-vanilla-danger-zone-case",
    "ursus-knife-case-hardened-danger-zone-case",
    "ursus-knife-fade-danger-zone-case",
    "ursus-knife-stained-danger-zone-case",
    "ursus-knife-blue-steel-danger-zone-case",
    "ursus-knife-boreal-forest-danger-zone-case",
    "ursus-knife-safari-mesh-danger-zone-case",
    "ursus-knife-night-stripe-danger-zone-case",
    "ursus-knife-crimson-web-danger-zone-case",
    "ursus-knife-urban-masked-danger-zone-case",
    "ursus-knife-forest-ddpat-danger-zone-case",
    "ursus-knife-scorched-danger-zone-case",
    "navaja-knife-slaughter-danger-zone-case",
    "navaja-knife-vanilla-danger-zone-case",
    "navaja-knife-case-hardened-danger-zone-case",
    "navaja-knife-fade-danger-zone-case",
    "navaja-knife-stained-danger-zone-case",
    "navaja-knife-blue-steel-danger-zone-case",
    "navaja-knife-boreal-forest-danger-zone-case",
    "navaja-knife-safari-mesh-danger-zone-case",
    "navaja-knife-night-stripe-danger-zone-case",
    "navaja-knife-crimson-web-danger-zone-case",
    "navaja-knife-scorched-danger-zone-case",
    "navaja-knife-urban-masked-danger-zone-case",
    "navaja-knife-forest-ddpat-danger-zone-case",
    "desert-eagle-code-red",
    "ak-47-neon-rider",
    "m4a1-s-nightmare",
    "famas-eye-of-athena",
    "sawed-off-devourer",
    "awp-paw",
    "cz75-auto-eco",
    "nova-toy-soldier",
    "mp7-powercore",
    "g3sg1-high-seas",
    "glock-18-warhawk",
    "p90-traction",
    "mp9-capillary",
    "r8-revolver-survivalist",
    "tec-9-snek-9",
    "dual-berettas-shred",
    "aug-amber-slipstream",
    "talon-knife-case-hardened-horizon-case",
    "talon-knife-fade-horizon-case",
    "talon-knife-stained-horizon-case",
    "talon-knife-blue-steel-horizon-case",
    "talon-knife-boreal-forest-horizon-case",
    "talon-knife-safari-mesh-horizon-case",
    "talon-knife-night-stripe-horizon-case",
    "talon-knife-forest-ddpat-horizon-case",
    "talon-knife-vanilla-horizon-case",
    "talon-knife-scorched-horizon-case",
    "talon-knife-slaughter-horizon-case",
    "talon-knife-crimson-web-horizon-case",
    "talon-knife-urban-masked-horizon-case",
    "stiletto-knife-crimson-web-horizon-case",
    "stiletto-knife-vanilla-horizon-case",
    "stiletto-knife-case-hardened-horizon-case",
    "stiletto-knife-fade-horizon-case",
    "stiletto-knife-stained-horizon-case",
    "stiletto-knife-blue-steel-horizon-case",
    "stiletto-knife-boreal-forest-horizon-case",
    "stiletto-knife-safari-mesh-horizon-case",
    "stiletto-knife-night-stripe-horizon-case",
    "stiletto-knife-forest-ddpat-horizon-case",
    "stiletto-knife-scorched-horizon-case",
    "stiletto-knife-slaughter-horizon-case",
    "stiletto-knife-urban-masked-horizon-case",
    "ursus-knife-slaughter-horizon-case",
    "ursus-knife-vanilla-horizon-case",
    "ursus-knife-case-hardened-horizon-case",
    "ursus-knife-fade-horizon-case",
    "ursus-knife-stained-horizon-case",
    "ursus-knife-blue-steel-horizon-case",
    "ursus-knife-boreal-forest-horizon-case",
    "ursus-knife-safari-mesh-horizon-case",
    "ursus-knife-night-stripe-horizon-case",
    "ursus-knife-crimson-web-horizon-case",
    "ursus-knife-urban-masked-horizon-case",
    "ursus-knife-forest-ddpat-horizon-case",
    "ursus-knife-scorched-horizon-case",
    "navaja-knife-slaughter-horizon-case",
    "navaja-knife-vanilla-horizon-case",
    "navaja-knife-case-hardened-horizon-case",
    "navaja-knife-fade-horizon-case",
    "navaja-knife-stained-horizon-case",
    "navaja-knife-blue-steel-horizon-case",
    "navaja-knife-boreal-forest-horizon-case",
    "navaja-knife-safari-mesh-horizon-case",
    "navaja-knife-night-stripe-horizon-case",
    "navaja-knife-crimson-web-horizon-case",
    "navaja-knife-scorched-horizon-case",
    "navaja-knife-urban-masked-horizon-case",
    "navaja-knife-forest-ddpat-horizon-case",
    "mp7-bloodsport",
    "m4a4-neo-noir",
    "usp-s-cortex",
    "awp-mortis",
    "aug-stymphalian",
    "glock-18-moonrise",
    "ump-45-arctic-wolf",
    "mag-7-swag-7",
    "negev-lionfish",
    "nova-wild-six",
    "sg-553-aloha",
    "five-seven-flame-test",
    "r8-revolver-grip",
    "xm1014-oxide-blaze",
    "mp9-black-sand",
    "pp-bizon-night-riot",
    "p2000-urban-hazard",
    "sport-gloves-vice-clutch-case",
    "sport-gloves-omega-clutch-case",
    "sport-gloves-amphibious-clutch-case",
    "sport-gloves-bronze-morph-clutch-case",
    "specialist-gloves-buckshot-clutch-case",
    "specialist-gloves-fade-clutch-case",
    "specialist-gloves-crimson-web-clutch-case",
    "specialist-gloves-mogul-clutch-case",
    "hydra-gloves-emerald-clutch-case",
    "hydra-gloves-mangrove-clutch-case",
    "hydra-gloves-rattler-clutch-case",
    "hydra-gloves-case-hardened-clutch-case",
    "hand-wraps-arboreal-clutch-case",
    "hand-wraps-duct-tape-clutch-case",
    "hand-wraps-cobalt-skulls-clutch-case",
    "hand-wraps-overprint-clutch-case",
    "moto-gloves-pow-clutch-case",
    "moto-gloves-polygon-clutch-case",
    "moto-gloves-transport-clutch-case",
    "moto-gloves-turtle-clutch-case",
    "driver-gloves-imperial-plaid-clutch-case",
    "driver-gloves-king-snake-clutch-case",
    "driver-gloves-overtake-clutch-case",
    "driver-gloves-racing-green-clutch-case",
    "p250-see-ya-later",
    "ak-47-the-empress",
    "m4a1-s-leaded-glass",
    "pp-bizon-high-roller",
    "r8-revolver-llama-cannon",
    "mp9-goo",
    "cz75-auto-tacticat",
    "sg-553-phantom",
    "ump-45-exposure",
    "xm1014-ziggy",
    "glock-18-off-world",
    "mac-10-oceanic",
    "tec-9-cracked-opal",
    "aug-triqua",
    "sawed-off-morris",
    "g3sg1-hunter",
    "scar-20-jungle-slipstream",
    "butterfly-knife-tiger-tooth-spectrum-2-case",
    "butterfly-knife-rust-coat-spectrum-2-case",
    "butterfly-knife-ultraviolet-spectrum-2-case",
    "butterfly-knife-damascus-steel-spectrum-2-case",
    "butterfly-knife-doppler-spectrum-2-case",
    "butterfly-knife-marble-fade-spectrum-2-case",
    "huntsman-knife-marble-fade-spectrum-2-case",
    "huntsman-knife-tiger-tooth-spectrum-2-case",
    "huntsman-knife-doppler-spectrum-2-case",
    "huntsman-knife-ultraviolet-spectrum-2-case",
    "huntsman-knife-damascus-steel-spectrum-2-case",
    "huntsman-knife-rust-coat-spectrum-2-case",
    "bowie-knife-doppler-spectrum-2-case",
    "bowie-knife-marble-fade-spectrum-2-case",
    "bowie-knife-tiger-tooth-spectrum-2-case",
    "bowie-knife-rust-coat-spectrum-2-case",
    "bowie-knife-ultraviolet-spectrum-2-case",
    "bowie-knife-damascus-steel-spectrum-2-case",
    "falchion-knife-marble-fade-spectrum-2-case",
    "falchion-knife-doppler-spectrum-2-case",
    "falchion-knife-damascus-steel-spectrum-2-case",
    "falchion-knife-tiger-tooth-spectrum-2-case",
    "falchion-knife-rust-coat-spectrum-2-case",
    "falchion-knife-ultraviolet-spectrum-2-case",
    "shadow-daggers-marble-fade-spectrum-2-case",
    "shadow-daggers-damascus-steel-spectrum-2-case",
    "shadow-daggers-tiger-tooth-spectrum-2-case",
    "shadow-daggers-doppler-spectrum-2-case",
    "shadow-daggers-ultraviolet-spectrum-2-case",
    "shadow-daggers-rust-coat-spectrum-2-case",
    "five-seven-hyper-beast",
    "awp-oni-taiji",
    "m4a4-hellfire",
    "galil-ar-sugar-rush",
    "dual-berettas-cobra-strike",
    "ak-47-orbit-mk01",
    "ssg-08-death-s-head",
    "p250-red-rock",
    "p2000-woodsman",
    "p90-death-grip",
    "usp-s-blueprint",
    "m4a1-s-briefing",
    "tec-9-cut-out",
    "ump-45-metal-flowers",
    "mac-10-aloha",
    "mag-7-hard-water",
    "famas-macabre",
    "bloodhound-gloves-bronzed-operation-hydra-case",
    "bloodhound-gloves-charred-operation-hydra-case",
    "bloodhound-gloves-guerrilla-operation-hydra-case",
    "bloodhound-gloves-snakebite-operation-hydra-case",
    "driver-gloves-convoy-operation-hydra-case",
    "driver-gloves-crimson-weave-operation-hydra-case",
    "driver-gloves-diamondback-operation-hydra-case",
    "driver-gloves-lunar-weave-operation-hydra-case",
    "hand-wraps-badlands-operation-hydra-case",
    "hand-wraps-leather-operation-hydra-case",
    "hand-wraps-slaughter-operation-hydra-case",
    "hand-wraps-spruce-ddpat-operation-hydra-case",
    "moto-gloves-boom-operation-hydra-case",
    "moto-gloves-cool-mint-operation-hydra-case",
    "moto-gloves-eclipse-operation-hydra-case",
    "moto-gloves-spearmint-operation-hydra-case",
    "specialist-gloves-crimson-kimono-operation-hydra-case",
    "specialist-gloves-emerald-web-operation-hydra-case",
    "specialist-gloves-forest-ddpat-operation-hydra-case",
    "specialist-gloves-foundation-operation-hydra-case",
    "sport-gloves-arid-operation-hydra-case",
    "sport-gloves-hedge-maze-operation-hydra-case",
    "sport-gloves-pandora-s-box-operation-hydra-case",
    "sport-gloves-superconductor-operation-hydra-case",
    "usp-s-neo-noir",
    "ak-47-bloodsport",
    "m4a1-s-decimator",
    "awp-fever-dream",
    "cz75-auto-xiangliu",
    "galil-ar-crimson-tsunami",
    "xm1014-seasons",
    "mac-10-last-dive",
    "ump-45-scaffold",
    "m249-emerald-poison-dart",
    "desert-eagle-oxide-blaze",
    "five-seven-capillary",
    "p250-ripple",
    "scar-20-blueprint",
    "pp-bizon-jungle-slipstream",
    "sawed-off-zander",
    "mp7-akoben",
    "butterfly-knife-tiger-tooth-spectrum-case",
    "butterfly-knife-rust-coat-spectrum-case",
    "butterfly-knife-ultraviolet-spectrum-case",
    "butterfly-knife-damascus-steel-spectrum-case",
    "butterfly-knife-doppler-spectrum-case",
    "butterfly-knife-marble-fade-spectrum-case",
    "huntsman-knife-marble-fade-spectrum-case",
    "huntsman-knife-tiger-tooth-spectrum-case",
    "huntsman-knife-doppler-spectrum-case",
    "huntsman-knife-ultraviolet-spectrum-case",
    "huntsman-knife-damascus-steel-spectrum-case",
    "huntsman-knife-rust-coat-spectrum-case",
    "bowie-knife-doppler-spectrum-case",
    "bowie-knife-marble-fade-spectrum-case",
    "bowie-knife-tiger-tooth-spectrum-case",
    "bowie-knife-rust-coat-spectrum-case",
    "bowie-knife-ultraviolet-spectrum-case",
    "bowie-knife-damascus-steel-spectrum-case",
    "falchion-knife-marble-fade-spectrum-case",
    "falchion-knife-doppler-spectrum-case",
    "falchion-knife-damascus-steel-spectrum-case",
    "falchion-knife-tiger-tooth-spectrum-case",
    "falchion-knife-rust-coat-spectrum-case",
    "falchion-knife-ultraviolet-spectrum-case",
    "shadow-daggers-marble-fade-spectrum-case",
    "shadow-daggers-damascus-steel-spectrum-case",
    "shadow-daggers-tiger-tooth-spectrum-case",
    "shadow-daggers-doppler-spectrum-case",
    "shadow-daggers-ultraviolet-spectrum-case",
    "shadow-daggers-rust-coat-spectrum-case",
    "ssg-08-dragonfire",
    "m4a4-buzz-kill",
    "famas-mecha-industries",
    "p90-shallow-grave",
    "sawed-off-wasteland-princess",
    "usp-s-cyrex",
    "m4a1-s-flashback",
    "dual-berettas-royal-consorts",
    "g3sg1-stinger",
    "nova-gila",
    "glock-18-ironwork",
    "mp7-cirrus",
    "p2000-turf",
    "galil-ar-black-sand",
    "mp9-sand-scale",
    "cz75-auto-polymer",
    "mag-7-sonar",
    "bloodhound-gloves-bronzed-glove-case",
    "bloodhound-gloves-charred-glove-case",
    "bloodhound-gloves-guerrilla-glove-case",
    "bloodhound-gloves-snakebite-glove-case",
    "driver-gloves-convoy-glove-case",
    "driver-gloves-crimson-weave-glove-case",
    "driver-gloves-diamondback-glove-case",
    "driver-gloves-lunar-weave-glove-case",
    "hand-wraps-badlands-glove-case",
    "hand-wraps-leather-glove-case",
    "hand-wraps-slaughter-glove-case",
    "hand-wraps-spruce-ddpat-glove-case",
    "moto-gloves-boom-glove-case",
    "moto-gloves-cool-mint-glove-case",
    "moto-gloves-eclipse-glove-case",
    "moto-gloves-spearmint-glove-case",
    "specialist-gloves-crimson-kimono-glove-case",
    "specialist-gloves-emerald-web-glove-case",
    "specialist-gloves-forest-ddpat-glove-case",
    "specialist-gloves-foundation-glove-case",
    "sport-gloves-arid-glove-case",
    "sport-gloves-hedge-maze-glove-case",
    "sport-gloves-pandora-s-box-glove-case",
    "sport-gloves-superconductor-glove-case",
    "ak-47-neon-revolution",
    "famas-roll-cage",
    "tec-9-fuel-injector",
    "mp9-airlock",
    "aug-syd-mead",
    "desert-eagle-directive",
    "glock-18-weasel",
    "mag-7-petroglyph",
    "scar-20-powercore",
    "sg-553-triarch",
    "xm1014-slipstream",
    "p90-grim",
    "g3sg1-ventilator",
    "cz75-auto-imprint",
    "negev-dazzle",
    "ump-45-briefing",
    "five-seven-scumbria",
    "bayonet-autotronic-gamma-2-case",
    "bayonet-black-laminate-gamma-2-case",
    "bayonet-bright-water-gamma-2-case",
    "bayonet-freehand-gamma-2-case",
    "bayonet-gamma-doppler-gamma-2-case",
    "bayonet-lore-gamma-2-case",
    "flip-knife-autotronic-gamma-2-case",
    "flip-knife-black-laminate-gamma-2-case",
    "flip-knife-bright-water-gamma-2-case",
    "flip-knife-freehand-gamma-2-case",
    "flip-knife-gamma-doppler-gamma-2-case",
    "flip-knife-lore-gamma-2-case",
    "gut-knife-autotronic-gamma-2-case",
    "gut-knife-black-laminate-gamma-2-case",
    "gut-knife-bright-water-gamma-2-case",
    "gut-knife-freehand-gamma-2-case",
    "gut-knife-gamma-doppler-gamma-2-case",
    "gut-knife-lore-gamma-2-case",
    "karambit-black-laminate-gamma-2-case",
    "karambit-bright-water-gamma-2-case",
    "karambit-freehand-gamma-2-case",
    "karambit-lore-gamma-2-case",
    "karambit-autotronic-gamma-2-case",
    "karambit-gamma-doppler-gamma-2-case",
    "m9-bayonet-autotronic-gamma-2-case",
    "m9-bayonet-black-laminate-gamma-2-case",
    "m9-bayonet-bright-water-gamma-2-case",
    "m9-bayonet-freehand-gamma-2-case",
    "m9-bayonet-gamma-doppler-gamma-2-case",
    "m9-bayonet-lore-gamma-2-case",
    "glock-18-wasteland-rebel",
    "m4a1-s-mecha-industries",
    "m4a4-desolate-space",
    "p2000-imperial-dragon",
    "scar-20-bloodsport",
    "awp-phobos",
    "aug-aristocrat",
    "p90-chopper",
    "r8-revolver-reboot",
    "sawed-off-limelight",
    "five-seven-violent-daimyo",
    "tec-9-ice-cap",
    "sg-553-aerial",
    "nova-exo",
    "mac-10-carnivore",
    "p250-iron-clad",
    "pp-bizon-harvester",
    "bayonet-autotronic-gamma-case",
    "bayonet-black-laminate-gamma-case",
    "bayonet-bright-water-gamma-case",
    "bayonet-freehand-gamma-case",
    "bayonet-gamma-doppler-gamma-case",
    "bayonet-lore-gamma-case",
    "flip-knife-autotronic-gamma-case",
    "flip-knife-black-laminate-gamma-case",
    "flip-knife-bright-water-gamma-case",
    "flip-knife-freehand-gamma-case",
    "flip-knife-gamma-doppler-gamma-case",
    "flip-knife-lore-gamma-case",
    "gut-knife-autotronic-gamma-case",
    "gut-knife-black-laminate-gamma-case",
    "gut-knife-bright-water-gamma-case",
    "gut-knife-freehand-gamma-case",
    "gut-knife-gamma-doppler-gamma-case",
    "gut-knife-lore-gamma-case"
}

def normalize_name(name):
    # Remove | and extra spaces, convert to lower case, replace spaces with hyphens
    name = name.replace("|", "").strip()
    # Remove multiple spaces
    name = re.sub(r'\s+', ' ', name)
    return name.lower().replace(" ", "-")

def get_case_name_from_url(url):
    path = urlparse(url).path
    # Example: /case/422/Fever-Case
    parts = path.split('/')
    if parts:
        return parts[-1].lower()
    return ""

import shutil

def download_image(url, filename, folder="images"):
    if not os.path.exists(folder):
        os.makedirs(folder)
    
    dest_path = os.path.join(folder, filename)
    if os.path.exists(dest_path):
        print(f"Skipping {filename}, already exists.")
        return

    # Check if it's a local file (from saved HTML)
    if os.path.exists(url):
        try:
            shutil.copy(url, dest_path)
            print(f"Copied local file to {filename}")
            return
        except Exception as e:
            print(f"Error copying local file {url}: {e}")
            return

    # Otherwise try downloading
    try:
        headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
        }
        response = requests.get(url, headers=headers)
        if response.status_code == 200:
            with open(dest_path, 'wb') as f:
                f.write(response.content)
            print(f"Downloaded {filename}")
        else:
            print(f"Failed to download {url}: Status {response.status_code}")
    except Exception as e:
        print(f"Error downloading {url}: {e}")

def process_source(source):
    html = ""
    case_name = ""
    
    if os.path.isfile(source):
        print(f"Reading from file: {source}")
        with open(source, 'r', encoding='utf-8') as f:
            html = f.read()
        
        # Derive case name from filename
        base = os.path.splitext(os.path.basename(source))[0]
        # Remove common suffix from "Save As"
        base = base.replace(" Skins - CS2 Skins", "")
        # Normalize and handle underscores
        case_name = normalize_name(base).replace("_", "-")
    else:
        print(f"Processing URL: {source}")
        case_name = get_case_name_from_url(source)

        headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
            "Accept-Language": "en-US,en;q=0.9",
            "Referer": "https://stash.clash.gg/",
            "Upgrade-Insecure-Requests": "1"
        }
        
        try:
            response = requests.get(source, headers=headers)
            response.raise_for_status()
            html = response.text
        except Exception as e:
            print(f"Failed to fetch page: {e}")
            print("Tip: If you get a 403 Forbidden error, the site is protected. Save the page as HTML (e.g., 'fever-case.html') and run the script on that file.")
            return

    print(f"Case name derived: {case_name}")

    # Regex to find images with alt text
    # <img class="..." src="..." alt="...">
    # We look for src and alt attributes. Order might vary, so we scan for img tags first.
    
    img_tags = re.findall(r'<img[^>]+>', html)
    
    for tag in img_tags:
        # Extract src
        src_match = re.search(r'src="([^"]+)"', tag)
        # Extract alt
        alt_match = re.search(r'alt="([^"]+)"', tag)
        
        if src_match and alt_match:
            src = html_module.unescape(src_match.group(1))
            alt = html_module.unescape(alt_match.group(1))
            
            # Filter: Only keep images with '512fx384f' or 'light_large' in the URL
            if "512fx384f" not in src and "light_large" not in src:
                # print(f"Skipping {alt} - URL does not contain 512fx384f or light_large")
                continue

            # Skip if alt is empty or generic
            if not alt or alt.lower() == "image":
                continue

            normalized = normalize_name(alt)
            
            # Candidates
            # User requested to use just the slug name without the case suffix
            found_slug = normalized
            
            if found_slug:
                print(f"Processing: '{alt}' -> {found_slug} (High Res)")
                # Check if src is a valid URL
                if src.startswith("//"):
                    src = "https:" + src
                elif src.startswith("/"):
                    src = "https://stash.clash.gg" + src # Assuming base
                
                download_image(src, f"{found_slug}.png", folder=r"C:\Users\jojon\Desktop\csinvest\csinvest-frontend\src\assets\skins")
            else:
                # print(f"No match for '{alt}' (Normalized: {normalized})")
                pass

import glob

if __name__ == "__main__":
    # Process all HTML files in the current directory
    html_files = glob.glob("*.html")
    
    if not html_files:
        print("No HTML files found in the current directory.")
    else:
        print(f"Found {len(html_files)} HTML files to process.")
        for f in html_files:
            process_source(f)
